### ISSUE TITLE
Platform Issue

### ISSUE THREAD

**Issue by holyCherryPerry** [Dukobpa3/Duk_FST_Packed_0#10]
Hi! Really like you update work with these theme, but i found these issue. I know that logicaly it's best to left pc platform, but i really like to save for many platform that i can. Can this be fixed?
![Playnite FullscreenApp_S9mJYXmXY4](https://user-images.githubusercontent.com/122989153/213185647-9c1db80f-bc8c-4e48-a0df-d60b8aa9f259.jpg)
And in addition to the question, please give the opportunity to put video intro for authenticity) I understand that this was not in the original theme, but I have no idea how to write it into the code myself so that everything works.
Thanks for your work

**Comment by dukobpa3** [comment]
hmm
maybe there should be icons.
I'll try

**Comment by dukobpa3** [comment]
Video intro you mean on start system?

**Comment by dukobpa3** [comment]
Make different issue for video please.
I've changed layout a little so platforms looking good now.

**Comment by holyCherryPerry** [comment]
Ok, got it. Thx
