### ISSUE TITLE
New Update: Issue with language in HLTB

### ISSUE THREAD

**Issue by holyCherryPerry** [Dukobpa3/Duk_FST_Packed_0#11]
Hi again. Thx for update. But I notice issue with HLTB addon in russian (i donno about different language).
In english - it's looking good:
![Playnite FullscreenApp_GuEJ6TuIoO](https://user-images.githubusercontent.com/122989153/214025682-f645c264-f336-4841-b378-b1d76f4cddca.png)
In different language not so good
![Playnite FullscreenApp_hF3ad59lca](https://user-images.githubusercontent.com/122989153/214025961-62a4d2b6-236b-4932-a699-96a2a83b4d92.png)
Russian
![Playnite FullscreenApp_lXJFjg09oQ](https://user-images.githubusercontent.com/122989153/214026011-0d2fc406-b6cb-4aea-bd19-b9e5436dc522.png)
Ukranian
And maybe this problem exists in other languages. If you need i can look for it.

And in addition. About year release and developer and platform info: is it right that info plased in top left coner or it's should be icon?
If it's should be icon: which folder should I put the icons in?

**Comment by dukobpa3** [comment]
Sad about localized strings. Forgot to check ukrainian) I'm using english in Playnite by many reasons. There is also issues with localized tags, filters etc, so much simpler just use eng

I'll try to do something but there not so much place
Maybe enable wrapping but I think it will look bit more ugly

**Comment by dukobpa3** [comment]
Top-left corner not an icon, it is formatted text about Platforms, Developers and Publishers. For platforms I will try to find solution with icons, but Developers and Publishers not.

I'm also not sure it is final place for this info panel, need to look on it couple days. I think I'll move it in some another place

**Comment by dukobpa3** [comment]
Changed a little

![image](https://user-images.githubusercontent.com/1858880/214669671-8d495b66-987b-4c22-a313-7f92c5abe1e6.jpeg)

**Comment by holyCherryPerry** [comment]
Nice work. Really love this theme.
