### ISSUE TITLE
Suggestion about Intro Video 

### ISSUE THREAD

**Issue by holyCherryPerry** [Dukobpa3/Duk_FST_Packed_0#12]
About video intro.
But going back to the original question, there is a fullscreen theme called [PS5ish](https://playnite.link/forum/thread-492.html). It's work with ExtraMedia addon.
And there you can put video intro when lauch fullscreen mode, it's doing this:

https://user-images.githubusercontent.com/122989153/214033030-6fb45eea-da24-4b5a-9726-b94fe9c177a3.mp4

When i wrote about this first time, i donno about Playnite Addon called - Splash Screen. It's can put intro video when you launch game like this:

https://user-images.githubusercontent.com/122989153/214028618-836171ac-251e-4521-8dd5-fb4d2291c08b.mp4

So, i say i fixed my video intro myself) So i donno need this intro idea or dump it)
Sorry for 480p nonsense, but github have video size limits.
And thx again for good work.

**Comment by dukobpa3** [comment]
Theme intro video – I don't like it from technical reason because whole theme will be more heavy and not so fast as now (this videos integrates directly to Games List view, so Games List workin slower with them)

Game intro video – yes, use SplashScreen for it. I'm using it also)

**Comment by holyCherryPerry** [comment]
Ok, thx
