### ISSUE TITLE
Get rid of the video control when video player has been disabled

### ISSUE THREAD

**Issue by beam05** [Dukobpa3/Duk_FST_Packed_0#14]
I use ExtraMetadata for logos but I don't really like to have trailers on the pages so I never have the function enabled. The theme still displays video controls like in the picture. It should be gone automatically if we don't have the function enabled or there should be an option to get rid of it.

![bbbbbb](https://user-images.githubusercontent.com/132223392/235403300-aa1dabda-db95-4b86-b5f2-7964fa8bd2a9.png)

**Comment by dukobpa3** [comment]
v.2.0
