### ISSUE TITLE
Game logos too big

### ISSUE THREAD

**Issue by testingthisout12345** [Dukobpa3/Duk_FST_Packed_0#16]
In the details view of games the logos are way too big (getting cropped out), and the games are displaying text names in some cases with the logos visible. Is there a way to make the logos scale down & hide the names of games while logos are visible?

**Comment by dukobpa3** [comment]
Make couple screenshots with explanation please

**Comment by testingthisout12345** [comment]
Too big
![image](https://github.com/Dukobpa3/Duk_FST_Packed_0/assets/19291422/913dde57-9228-43b5-b9bd-c65056fb57fc)
![image](https://github.com/Dukobpa3/Duk_FST_Packed_0/assets/19291422/820ca940-5321-4e02-9bf9-7a84d7df397d)

Fine
![image](https://github.com/Dukobpa3/Duk_FST_Packed_0/assets/19291422/86c8ccfb-3a80-401a-a077-79e714f612ef)
![image](https://github.com/Dukobpa3/Duk_FST_Packed_0/assets/19291422/1e900f67-f173-4e76-a4a8-49f26b4b5845)

Is there a way to scale them down (same way as covers can be set)? Also in Fullscreen mode. They get "clipped out" if they're too big.

**Comment by dukobpa3** [comment]
@TheJAXi It is screens of some other theme)))
My own looks totally different)
