### ISSUE TITLE
Console Logos at the Top Not Showing 

### ISSUE THREAD

**Issue by will197** [Dukobpa3/Duk_FST_Packed_0#18]
Saw on reddit you mentioned you uploaded the wrong version. Think you're able to put the version back with logos at the top?

**Comment by flopezluksenberg** [comment]
There is an explanation about it here: https://www.reddit.com/r/playnite/comments/y6jqni/comment/kp9civ7

**Comment by Droppisalt** [comment]
Having the same issue.

@flopezluksenberg not sure what I can do from the comment you linked. Any way to fix it myself? Not sure when @Dukobpa3 will be able to look into it
> There is an explanation about it here: [reddit.com/r/playnite/comments/y6jqni/comment/kp9civ7](https://www.reddit.com/r/playnite/comments/y6jqni/comment/kp9civ7)

**Comment by tedhinklater** [comment]
> Having the same issue.
> 
> @flopezluksenberg not sure what I can do from the comment you linked. Any way to fix it myself? Not sure when @Dukobpa3 will be able to look into it
> 

So go into AppData\Roaming\Playnite\Themes\Fullscreen\Duk_FST_4e173c94-69a2-48de-938b-6feb2b393bc9\CustomControls\ and open FilterPresetSelector.xaml

on line 28 where it says PathFormat='Icons/Filters/Squared/{0}.png'}"/
change it to PathFormat='Icons/Filters/{0}.png'}"/>

That'll get most icons loaded. If some don't (for example my Gamecube icon was still just text) just go back to the Duk_FST folder, then open folder Icons\Filters\ and rename the logo that isn't loading. In my example I renamed Nintendo Gamecube.png to just Gamecube.png and it loaded.

**Comment by Droppisalt** [comment]
@tedhinklater Thanks a bunch! That worked

**Comment by will197** [comment]
@tedhinklater worked perfect thanks. I'm just stuck on Nintendo Switch. Tried to rename it to Switch but didn't show up. Any other suggestions?

**Comment by tedhinklater** [comment]
> @tedhinklater worked perfect thanks. I'm just stuck on Nintendo Switch. Tried to rename it to Switch but didn't show up. Any other suggestions?

Is the PNG in \icons\filters\ definitely named "Nintendo Switch.png" ? I'd assume it's a name mismatch somewhere

**Comment by will197** [comment]
Yep. Originally Nintendo Switch.png
Tried Switch.png didn't work.

**Comment by dukobpa3** [comment]
Sorry guys I've totally remade whole my home setup and don't have any windows PC right now to do some tech stuff. Only one I have is console-like gaming PC which I don't want to use as development one.

I hope I'll do some soon...

Would be great if I can develop playnite on mac, but currently it is impossible...

**Comment by will197** [comment]
These are tiny modifications which wouldn't take any effort to make. I'm sure you can find any pc somewhere.

**Comment by dukobpa3** [comment]
> These are tiny modifications which wouldn't take any effort to make. I'm sure you can find any pc somewhere.

But should I? ))
I prefer to make it in comfortable way.

PS. Been working on new theme from scratch for some time, maybe will share it soon also.

**Comment by will197** [comment]
Yeah I think you should. You've been talking about fixing these logos for a
while. Others have helped. I don't think it requires any necessary comfort.
It's just logo linking which is almost done.

**Comment by dukobpa3** [comment]
Theme packer available only for windows, thats the issue
But maybe there is simple zip format, I'll check.

**Comment by dukobpa3** [comment]
If you so smart fell free to make pull request. Why not?

**Comment by dukobpa3** [comment]
Yeah, this is luck. There is a simple zip.

Fixed.

**Comment by Droppisalt** [comment]
> Yeah, this is luck. There is a simple zip.
> 
> Fixed.

Thanks a bunch! And don't listen to the others. It's just a theme, update it if you feel like it, no one's gonna die if some features aren't optimal. Looking forward to your new theme too!
