### ISSUE TITLE
Using Fill instead of Fit for background images.

### ISSUE THREAD

**Issue by shahiljain** [Dukobpa3/Duk_FST_Packed_0#9]
### Description
Some custom banners usually don't macth screen resolutions so using Fill (where the image gets cropped to screen size) will make it look much cleaner

### How it looks on Reskin XBOXSX Ext
![image](https://user-images.githubusercontent.com/75173792/205434845-2d2dd06a-066c-44d0-aee8-1c77c4a8326f.png)

### How it looks on Reskin XBOXSX
![image](https://user-images.githubusercontent.com/75173792/205434866-124161ff-1c51-417d-b0e2-43b36104919c.png)

**Comment by dukobpa3** [comment]
I've made it exact for 1920-620 backs

Will try to play with another dimensions. I think it will be horizontal scale with snap to top.

**Comment by beam05** [comment]
Please don't do this. This is probably the only theme that doesn't always try to fill the whole screen and it's why I use it. Other themes make the default Steam hero resolution look even worse on 4K screen by trying to fill the screen.

**Comment by dukobpa3** [comment]
I don't want to change it ))
